### ISSUE TITLE
GUI‐1. Select state to display (required) (SD)

### ISSUE THREAD

**Issue by kaitchau** [SBU-CSE-416/votifier#65]
The user can pick a state through a dropdown menu or possibly through clicking on the state in a map of the US. The state selection will cause a table to be displayed that contains a summary of the ensembles available for the state. Ensemble data in the table will include the number of district plans in the ensemble and the population equality threshold used in the MCMC computation. In addition, state selection will also cause the map of the state to be displayed as described in GUI-2.

**Comment by tonybuii2003** [comment]
SubTask: somehtnkg
